// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXMziw6yDA9I3gPzdcwD4_EI0RTk3D5B0',
    appId: '1:157878139478:web:2e5277108d8ea441e699f7',
    messagingSenderId: '157878139478',
    projectId: 'cahilliginle-yuzles',
    authDomain: 'cahilliginle-yuzles.firebaseapp.com',
    storageBucket: 'cahilliginle-yuzles.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3k-mBSeJrI05k-yqw9_okVvf97IN2mhE',
    appId: '1:157878139478:android:f3ca31d4f8ebc883e699f7',
    messagingSenderId: '157878139478',
    projectId: 'cahilliginle-yuzles',
    storageBucket: 'cahilliginle-yuzles.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUilxlYcy1WhH1HbIsuwE_jr-Mf3oXZkI',
    appId: '1:157878139478:ios:3183cd079742aba5e699f7',
    messagingSenderId: '157878139478',
    projectId: 'cahilliginle-yuzles',
    storageBucket: 'cahilliginle-yuzles.firebasestorage.app',
    iosBundleId: 'com.example.ilkUygulamam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUilxlYcy1WhH1HbIsuwE_jr-Mf3oXZkI',
    appId: '1:157878139478:ios:3183cd079742aba5e699f7',
    messagingSenderId: '157878139478',
    projectId: 'cahilliginle-yuzles',
    storageBucket: 'cahilliginle-yuzles.firebasestorage.app',
    iosBundleId: 'com.example.ilkUygulamam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXMziw6yDA9I3gPzdcwD4_EI0RTk3D5B0',
    appId: '1:157878139478:web:069acf92d10e18d6e699f7',
    messagingSenderId: '157878139478',
    projectId: 'cahilliginle-yuzles',
    authDomain: 'cahilliginle-yuzles.firebaseapp.com',
    storageBucket: 'cahilliginle-yuzles.firebasestorage.app',
  );
}
